[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[profile.release]
codegen-units = 1
lto = "fat"

[dev-dependencies]
rstest = "0.26.1"

[dependencies]
indicatif = {version = "0.18.3", features = ["rayon"] }
itertools = "0.14.0"
rayon = "1.11.0"
